import { useEffect, useState } from 'react';
import { FlaskConical, RefreshCw } from 'lucide-react';
type Report={id:string;mode:string;questions:number;answerable_text_questions:number;unanswerable_questions:number;errors:number;expected_span_answer_rate:number;unanswerable_abstention_rate:number;retrieval_evidence_hit_rate_at_10:number;tool_value_pass_rate:number;latency_p95_ms:number;categories:Record<string,{questions:number;expected_span_answer_rate:number|null}>};
const percent=(n:number)=>`${(n*100).toFixed(1)}%`;
export function EvaluationDashboard(){
 const [reports,setReports]=useState<Report[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 async function refresh(){setLoading(true);setError('');try{const r=await fetch('/api/evaluations');if(!r.ok)throw Error('Could not load recorded evaluations.');setReports(await r.json());}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[]);
 const latest=reports.filter(r=>r.id.startsWith('expanded'));
 return <div className="content evaluation"><div className="eyebrow"><FlaskConical size={13}/> MEASURE, THEN IMPROVE</div><h1>Show your evidence.<br/><span>Know your limits.</span></h1><p className="intro">Recorded development evaluations across documents, OCR images, and CSV tools.<br/>These results describe fictional sample data, not production accuracy.</p>
 <button className="refresh-button" disabled={loading} onClick={refresh}><RefreshCw size={14}/> {loading?'Loading…':'Refresh recorded results'}</button>{error&&<p role="alert" className="error">{error}</p>}
 {!loading&&!reports.length&&!error&&<p className="muted">Run the expanded evaluation scripts to create reports.</p>}
 <div className="eval-cards">{latest.map(r=><article className="eval-card" key={r.id}><span className="mode-label">{r.mode==='ollama'?'Local AI · Qwen 2.5 1.5B':'Source excerpts'}</span><h2>{r.questions} questions</h2><p>{r.answerable_text_questions} factual · {r.unanswerable_questions} missing facts</p>{[['Expected answer text',r.expected_span_answer_rate],['Exact missing-fact refusal',r.unanswerable_abstention_rate],['Retrieved expected evidence',r.retrieval_evidence_hit_rate_at_10],['CSV values matched',r.tool_value_pass_rate]].map(([label,value])=><div className="eval-measure" key={String(label)}><div><span>{label}</span><strong>{percent(Number(value))}</strong></div><meter min="0" max="1" value={Number(value)} aria-label={String(label)}/></div>)}<small>P95 full response: {r.latency_p95_ms.toFixed(1)} ms · {r.errors} request errors</small></article>)}</div>
 {!!reports.length&&<><h2 className="eval-section-title">Before and after</h2><div className="table-scroll"><table><thead><tr><th>Recorded run</th><th>Expected text</th><th>Exact refusal</th><th>P95 response</th></tr></thead><tbody>{reports.map(r=><tr key={r.id}><td>{r.mode==='ollama'?'Local AI':'Excerpts'} · {r.id.startsWith('baseline')?'before':'latest'}</td><td>{percent(r.expected_span_answer_rate)}</td><td>{percent(r.unanswerable_abstention_rate)}</td><td>{r.latency_p95_ms.toFixed(1)} ms</td></tr>)}</tbody></table></div></>}
 <div className="evaluation-note"><strong>What these numbers mean</strong><p>Expected-text matching can miss a correct paraphrase or count an answer containing unrelated facts. Valid source references do not establish factual accuracy. Exact refusal counts only the standard missing-evidence message.</p><p>The 62-question dataset was authored alongside this project and used to guide improvements. Results need independent human review and broader testing. Response times are sequential, complete answers; they do not measure streaming or concurrent load.</p></div><footer><span>Reproducible reports · Local execution</span><span>Development set · 62 questions</span></footer></div>;
}
